name: in_app_review_example
description: A demo using in_app_review
version: 0.0.1
publish_to: 'none'
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  in_app_review: ^2.0.8
flutter:

