name: flutter_staggered_grid_view_example
description: A demo using flutter_staggered_grid_view
version: 0.0.1
publish_to: 'none'
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
flutter:

