name: dots_indicator_example
description: A demo using dots_indicator
version: 0.0.1
publish_to: 'none'
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  dots_indicator: ^3.0.0
flutter:

